version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    image: node-prom-grafana-backend
    ports:
      - "3000:3000"
    #env_file: ./env

  prometheus:
    image: prom/prometheus:v2.37.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data:
