version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    image: node-prom-grafana-backend
    ports:
      - "3000:3000"
    #env_file: ./env
